version : "3.8"

services :
 mongodb :
  # image automatiquement chargé par docker
  image: mongo:7.0
  container_name : randoDB # nom du conteneur
  restart: always


  ports:
   - "27017:27017" # TOOD revoir le port

  environment :
    MONGO_INITDB_ROOT_USERNAME: admin
    MONGO_INITDB_ROOT_PASSWORD: juste1234
    MONGO_INITDB_DATABASE: Rodeo-db

  volumes:
    - mongodb_data:/data/db 
    - ./init:docker-entrypoint-initdb.d:ro # ./init -> dans le dossier init on récupère tous les fichiers script et on les lance dans le dossier spécial de l'image mongo

volumes :
  mongodb_data:
  
