version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: randoDB
    restart: always

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: juste1234
      MONGO_INITDB_DATABASE: Roadeo-db

    volumes:
      - mongodb_data:/data/db

  springBoot:
    image: jelastic/springboot:temurinjdk-21.0.8-almalinux-9
    container_name: randoSpring
    restart: always

    ports:
      - "8080:8080"  

    depends_on:
      - mongodb   

volumes:
  mongodb_data:
