spring.application.name=roadeo
#spring.data.mongodb.uri=mongodb://admin:juste1234@localhost:27017/Roadeo-db
spring.data.mongodb.uri=mongodb://admin:juste1234@localhost:27017/Roadeo-db?authSource=admin

