spring.application.name=roadeo
server.port=8080

# Utilise la variable d'environnement SPRING_DATA_MONGODB_URI si définie,
# sinon tombe sur localhost
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://admin:juste1234@localhost:27017/Roadeo-db?authSource=admin}

# Actuator / Metrics
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.roadeo.sacados.total=true
management.metrics.distribution.percentiles-histogram.roadeo.sacados.algorithm=true
