name: Couverture API et application Android

# Déclenchement sur push vers main et integration
on:
  workflow_dispatch:
  push:
    branches: [ main, api, actions-tests ]

jobs:
  
  Tests-API:
    
    runs-on: ubuntu-latest
    steps:
      
      # Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer Java JDK 20
      - name: Setup JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      # ========= Tests de l'API =========

      # Générer les rapports qualité
      - name: Maven build and tests
        working-directory: roadeo_api
        run: mvn clean verify

      # Générer le rapport de couverture (JaCoCo)
      - name: Generate code coverage
        working-directory: roadeo_api
        run: mvn jacoco:report
        
  Tests-Android:
    
    runs-on: ubuntu-latest
    steps:
      
      # Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer Java JDK 20
      - name: Setup JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
      
      # ========= Tests de l'application Android =========
        
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Tests 
        working-directory: "Application Android"
        run: chmod +x gradlew && ./gradlew test --stacktrace